import { Container } from "@/components/ui/Container";
import { Link } from "@/i18n/navigation";
import { LegalSection } from "./LegalSection";

/**
 * English version of the Terms of use. Section ids match the French version
 * (TermsOfServiceContent.tsx) so anchors stay stable. Translation provided for
 * convenience: have it reviewed by a legal professional before relying on it.
 */
export const termsOfServiceSectionsEn = [
  { id: "objet", title: "Purpose and scope" },
  { id: "acceptation", title: "Acceptance of the terms" },
  { id: "description-service", title: "Description of the service" },
  { id: "compte", title: "Account creation and management" },
  { id: "comptes-entreprise", title: "Company accounts and roles" },
  { id: "connexion-tiers", title: "Signing in with Google and Facebook" },
  { id: "contenu-utilisateur", title: "Your content and your data" },
  { id: "obligations", title: "Obligations and permitted use" },
  { id: "propriete-intellectuelle", title: "Intellectual property" },
  { id: "tarifs", title: "Pricing and billing" },
  { id: "disponibilite", title: "Availability and changes to the service" },
  { id: "responsabilite", title: "Limitation of liability" },
  { id: "suspension", title: "Suspension and termination" },
  { id: "modification", title: "Changes to these terms" },
  { id: "droit-applicable", title: "Governing law and disputes" },
  { id: "contact", title: "Contact" },
];

export function TermsOfServiceContentEn() {
  return (
    <Container>
      <div className="mx-auto max-w-3xl py-4">
        <LegalSection id="objet" title="1. Purpose and scope">
          <p>
            These Terms of use (the &ldquo;Terms&rdquo;) govern access to and use of the KIYANZA
            platform (the &ldquo;Service&rdquo;), published by <strong>Kiyanza</strong>, whose
            registered office is located in <strong>Douala, Cameroon</strong>, reachable at{" "}
            <strong>696370479</strong>, and registered under number{" "}
            <strong>CM-DLA-01-2026-B12-00529</strong> (hereinafter &ldquo;KIYANZA&rdquo;,
            &ldquo;we&rdquo;).
          </p>
          <p>
            They apply to any individual or legal entity (&ldquo;you&rdquo;, the
            &ldquo;User&rdquo;) accessing the Service, whether through the <strong>kiyanza.com</strong>{" "}
            website or any associated application.
          </p>
        </LegalSection>

        <LegalSection id="acceptation" title="2. Acceptance of the terms">
          <p>
            Creating an account, signing in with Google or Facebook, or using the Service in any way
            constitutes full acceptance of these Terms and of our{" "}
            <Link href="/politique-confidentialite">Privacy policy</Link>. If you do not accept
            these Terms, you must not use the Service.
          </p>
          <p>
            If you create an account on behalf of a company or organisation, you represent that you
            have the authority to bind that entity, which is then deemed the &ldquo;User&rdquo; within
            the meaning of these Terms.
          </p>
        </LegalSection>

        <LegalSection id="description-service" title="3. Description of the service">
          <p>KIYANZA is a marketing campaign management platform that notably allows you to:</p>
          <ul>
            <li>create, schedule and track marketing campaigns (field and digital) and their distribution channels;</li>
            <li>connect social media accounts (Facebook, Instagram) to run and track digital campaigns;</li>
            <li>receive recommendations and simulations generated by an intelligent assistant;</li>
            <li>track the execution of field services, with proof and QR code validation;</li>
            <li>
              manage tasks, notifications and users within the same company, with differentiated roles
              and access levels.
            </li>
          </ul>
          <p>
            KIYANZA reserves the right to change, add or remove features of the Service at any time,
            in particular for technical, legal or security reasons.
          </p>
        </LegalSection>

        <LegalSection id="compte" title="4. Account creation and management">
          <p>
            Access to most features requires creating an account, either with an email address and
            password or through a third-party provider (Google or Facebook — see the dedicated section
            below).
          </p>
          <p>
            You agree to provide accurate and up-to-date information and to keep your login
            credentials confidential. You are responsible for any activity carried out from your
            account. Notify us without delay at the address given in the &ldquo;Contact&rdquo; section
            if you suspect unauthorised access.
          </p>
        </LegalSection>

        <LegalSection id="comptes-entreprise" title="5. Company accounts and roles">
          <p>
            A user account may be attached to a company and assigned a role (for example
            administrator) that determines its level of access to that company&apos;s data and
            features. A company&apos;s administrator is responsible for managing their colleagues&apos;
            access, including deactivating the accounts of people who have left the organisation.
          </p>
          <p>
            KIYANZA does not arbitrate internal disputes within a client company regarding the
            allocation of roles or access to data: these matters are for the organisation concerned.
          </p>
        </LegalSection>

        <LegalSection id="connexion-tiers" title="6. Signing in with Google and Facebook">
          <p>
            You can create an account or sign in using your Google or Facebook account. In that case,
            we receive from these providers only the information strictly necessary to create your
            account (identifier, email address, first and last name) — see our{" "}
            <Link href="/politique-confidentialite">Privacy policy</Link> for details of the data
            processed.
          </p>
          <p>
            Your use of these third-party providers remains subject to their own terms of use and
            privacy policies, over which KIYANZA has no control.
          </p>
        </LegalSection>

        <LegalSection id="contenu-utilisateur" title="7. Your content and your data">
          <p>
            You remain the sole owner of the content you upload or create on the Service (campaign
            information, media, proof of execution, etc. — the &ldquo;Content&rdquo;). You grant us
            only the right to host, store, display and process this Content to the extent strictly
            necessary to provide the Service.
          </p>
          <p>
            You warrant that you hold all necessary rights to the Content you upload (in particular the
            media and visuals used in your campaigns) and that it does not infringe any third-party
            right or applicable law.
          </p>
        </LegalSection>

        <LegalSection id="obligations" title="8. Obligations and permitted use">
          <p>You agree not to:</p>
          <ul>
            <li>use the Service for illegal or fraudulent purposes or in breach of these Terms;</li>
            <li>attempt to gain unauthorised access to data or accounts belonging to other users or companies;</li>
            <li>
              disrupt the operation of the Service (introducing malware, deliberate overloading,
              circumventing security measures);
            </li>
            <li>use the Service&apos;s Google/Facebook integrations in breach of those platforms&apos; terms.</li>
          </ul>
        </LegalSection>

        <LegalSection id="propriete-intellectuelle" title="9. Intellectual property">
          <p>
            The KIYANZA brand, logo, interface, source code and all elements of the Service
            (excluding User Content) are the exclusive property of KIYANZA or its licensors and are
            protected by intellectual property law. Nothing in these Terms grants you any right to
            these elements beyond the right to use the Service granted by these Terms.
          </p>
        </LegalSection>

        <LegalSection id="tarifs" title="10. Pricing and billing">
          <p>
            The Service&apos;s plans and prices are described on our{" "}
            <Link href="/tarifs">Pricing</Link> page. Unless otherwise stated, prices exclude taxes
            and may change; any price change will be communicated to the Users concerned before it
            takes effect for ongoing subscriptions.
          </p>
        </LegalSection>

        <LegalSection id="disponibilite" title="11. Availability and changes to the service">
          <p>
            KIYANZA uses reasonable means to ensure the availability and security of the Service,
            without guaranteeing that it will be entirely free of interruptions. Planned or emergency
            maintenance may cause temporary interruptions, announced in advance whenever possible.
          </p>
        </LegalSection>

        <LegalSection id="responsabilite" title="12. Limitation of liability">
          <p>
            The Service is provided &ldquo;as is&rdquo;. To the extent permitted by applicable law,
            KIYANZA shall not be liable for indirect damages (loss of revenue, loss of data, loss of
            opportunity) resulting from the use of or inability to use the Service, including where
            such unavailability is caused by a third party (hosting provider, authentication provider,
            integrated social network).
          </p>
        </LegalSection>

        <LegalSection id="suspension" title="13. Suspension and termination">
          <p>
            You may stop using the Service and request the deletion of your account at any time by
            contacting us.
          </p>
          <p>
            KIYANZA may suspend or terminate an account&apos;s access, after notice where possible, in
            the event of a breach of these Terms, fraudulent use, or at the request of a competent
            authority.
          </p>
        </LegalSection>

        <LegalSection id="modification" title="14. Changes to these terms">
          <p>
            We may amend these Terms, in particular to reflect changes to the Service or a legal
            requirement. Any material change will be notified to you (by email or through the Service)
            before it takes effect. Continued use of the Service after notification constitutes
            acceptance of the amended Terms.
          </p>
        </LegalSection>

        <LegalSection id="droit-applicable" title="15. Governing law and disputes">
          <p>
            These Terms are governed by <strong>the law applicable in Cameroon</strong>. Any dispute
            relating to their interpretation or performance falls under the exclusive jurisdiction of
            the <strong>competent courts of Cameroon</strong>, unless mandatory public policy
            provisions provide otherwise.
          </p>
        </LegalSection>

        <LegalSection id="contact" title="16. Contact">
          <p>
            For any question about these Terms, you can contact us at:{" "}
            <strong>contact@kiyanza.com</strong>.
          </p>
        </LegalSection>
      </div>
    </Container>
  );
}
